name: flutter_persistence
description: A Flutter library for efficient data persistence using Hive as a local storage solution.
version: 0.0.2
repository: https://github.com/mgabriele00/flutter_persistence

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
